# Generated by Django 5.0.6 on 2025-09-25 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_mfa_enabled'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Cliente'), ('ANALISTA', 'Analista')], default='CLIENT', max_length=20),
        ),
        migrations.CreateModel(
            name='UserClientAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso Usuario-Cliente',
                'verbose_name_plural': 'Accesos Usuario-Cliente',
                'db_table': 'user_client_access',
                'unique_together': {('user', 'client')},
            },
        ),
    ]
