# Generated by Django 5.0.6 on 2025-08-29 06:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('CERTIFICATE_SUMMARY', 'Resumen de Certificados'), ('CERTIFICATE_DETAILED', 'Reporte Detallado de Certificados'), ('VULNERABILITY_SUMMARY', 'Resumen de Vulnerabilidades'), ('CLIENT_OVERVIEW', 'Vista General de Cliente')], max_length=50)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('JSON', 'JSON')], max_length=10)),
                ('frequency', models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral')], max_length=20)),
                ('filters', models.JSONField(default=dict)),
                ('email_recipients', models.JSONField(default=list, help_text='Lista de emails para envío automático')),
                ('active', models.BooleanField(default=True)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_schedules',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('CERTIFICATE_SUMMARY', 'Resumen de Certificados'), ('CERTIFICATE_DETAILED', 'Reporte Detallado de Certificados'), ('VULNERABILITY_SUMMARY', 'Resumen de Vulnerabilidades'), ('CLIENT_OVERVIEW', 'Vista General de Cliente')], max_length=50)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('JSON', 'JSON')], max_length=10)),
                ('filters', models.JSONField(default=dict, help_text='Filtros aplicados: fechas, tipos de certificados, etc.')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_certificates', models.PositiveIntegerField(blank=True, null=True)),
                ('total_analyses', models.PositiveIntegerField(blank=True, null=True)),
                ('total_vulnerabilities', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('client', models.ForeignKey(help_text='Cliente para el cual se genera el reporte', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='clients.client')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='reports_client__80ebc7_idx'), models.Index(fields=['requested_by', 'created_at'], name='reports_request_48ecc7_idx')],
            },
        ),
    ]
