# Generated by Django 5.0.6 on 2025-08-29 04:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SSL_TLS', 'SSL/TLS Analysis'), ('SSH', 'SSH Analysis'), ('WEB', 'Web Security Analysis'), ('FULL', 'Full Analysis')], max_length=50)),
                ('tuvo_exito', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('triggered_by', models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Programado'), ('API', 'API Call')], default='MANUAL', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='certs.certificate')),
            ],
            options={
                'db_table': 'analisis',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CadenaCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadena_ok', models.BooleanField(default=False)),
                ('errores', models.BooleanField(default=False)),
                ('autofirmado', models.BooleanField(default=False)),
                ('intermedios_extra', models.BooleanField(default=False)),
                ('chain_length', models.IntegerField(blank=True, null=True)),
                ('root_ca', models.CharField(blank=True, max_length=255)),
                ('intermediate_cas', models.TextField(blank=True, help_text='CAs intermedias (JSON)')),
                ('validation_errors', models.TextField(blank=True)),
                ('analisis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cadena_certificacion', to='analysis.analysis')),
            ],
            options={
                'db_table': 'cadena_certificacion',
            },
        ),
        migrations.CreateModel(
            name='OtrosParametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_respuesta_ssl', models.IntegerField(blank=True, help_text='Milisegundos', null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('handshake_time_ms', models.IntegerField(blank=True, null=True)),
                ('certificate_chain_size', models.IntegerField(blank=True, null=True)),
                ('compression_supported', models.BooleanField(null=True)),
                ('renegotiation_secure', models.BooleanField(null=True)),
                ('analisis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otros_parametros', to='analysis.analysis')),
            ],
            options={
                'db_table': 'otros_parametros',
            },
        ),
        migrations.CreateModel(
            name='ParametrosGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(blank=True, max_length=255)),
                ('san', models.TextField(blank=True, help_text='Subject Alternative Names (JSON)')),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=10)),
                ('algoritmo_firma', models.CharField(blank=True, max_length=100)),
                ('key_size', models.IntegerField(blank=True, null=True)),
                ('key_algorithm', models.CharField(blank=True, max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('dias_restantes', models.IntegerField(blank=True, null=True)),
                ('estado_revocacion', models.CharField(blank=True, max_length=50)),
                ('analisis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_generales', to='analysis.analysis')),
            ],
            options={
                'db_table': 'parametros_generales',
            },
        ),
        migrations.CreateModel(
            name='ParametrosSSH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=20)),
                ('protocolo', models.CharField(blank=True, max_length=10)),
                ('algoritmos', models.TextField(blank=True, help_text='Algoritmos soportados (JSON)')),
                ('algoritmos_mac', models.TextField(blank=True, help_text='Algoritmos MAC (JSON)')),
                ('algoritmos_debiles', models.TextField(blank=True, help_text='Algoritmos débiles (JSON)')),
                ('fingerprint', models.CharField(blank=True, max_length=255)),
                ('tipo_clave', models.CharField(blank=True, max_length=20)),
                ('longitud_clave', models.IntegerField(blank=True, null=True)),
                ('analisis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_ssh', to='analysis.analysis')),
            ],
            options={
                'db_table': 'parametros_ssh',
            },
        ),
        migrations.CreateModel(
            name='ParametrosTLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolos', models.TextField(blank=True, help_text='Protocolos soportados (JSON)')),
                ('cifrados_disponibles', models.TextField(blank=True, help_text='Lista de cifrados (JSON)')),
                ('cifrados_debiles', models.TextField(blank=True, help_text='Cifrados débiles encontrados (JSON)')),
                ('pfs', models.BooleanField(help_text='Perfect Forward Secrecy', null=True)),
                ('sslv2_supported', models.BooleanField(null=True)),
                ('sslv3_supported', models.BooleanField(null=True)),
                ('tls10_supported', models.BooleanField(null=True)),
                ('tls11_supported', models.BooleanField(null=True)),
                ('tls12_supported', models.BooleanField(null=True)),
                ('tls13_supported', models.BooleanField(null=True)),
                ('analisis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_tls', to='analysis.analysis')),
            ],
            options={
                'db_table': 'parametros_tls',
            },
        ),
        migrations.CreateModel(
            name='ParametrosWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsts', models.BooleanField(help_text='HTTP Strict Transport Security', null=True)),
                ('expect_ct', models.BooleanField(help_text='Certificate Transparency', null=True)),
                ('hpkp', models.BooleanField(help_text='HTTP Public Key Pinning', null=True)),
                ('fecha_hora_servidor', models.DateTimeField(blank=True, null=True)),
                ('sni', models.BooleanField(help_text='Server Name Indication', null=True)),
                ('ocsp_stapling', models.BooleanField(help_text='OCSP Stapling', null=True)),
                ('content_security_policy', models.TextField(blank=True)),
                ('x_frame_options', models.CharField(blank=True, max_length=50)),
                ('x_content_type_options', models.CharField(blank=True, max_length=50)),
                ('referrer_policy', models.CharField(blank=True, max_length=50)),
                ('analisis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_web', to='analysis.analysis')),
            ],
            options={
                'db_table': 'parametros_web',
            },
        ),
        migrations.CreateModel(
            name='Vulnerabilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerabilidad', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilidades', to='analysis.analysis')),
            ],
            options={
                'db_table': 'vulnerabilidades',
            },
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['certificado', 'tuvo_exito'], name='analisis_certifi_48ff3d_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['tipo', 'fecha_inicio'], name='analisis_tipo_9c525e_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerabilidades',
            index=models.Index(fields=['analisis', 'severity'], name='vulnerabili_analisi_b21426_idx'),
        ),
    ]
