# Generated by Django 5.0.6 on 2025-08-28 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClientAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_acceso', models.CharField(choices=[('lectura', 'Lectura'), ('escritura', 'Escritura')], max_length=20, verbose_name='Nivel de Acceso')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Acceso Usuario-Cliente',
                'verbose_name_plural': 'Accesos Usuario-Cliente',
            },
        ),
    ]
