# Generated by Django 5.0.6 on 2025-08-28 22:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_certificado', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('puerto', models.PositiveIntegerField()),
                ('protocolo', models.CharField(choices=[('HTTPS', 'HTTPS'), ('TLS', 'TLS'), ('SSH', 'SSH'), ('SMTP', 'SMTP'), ('IMAP', 'IMAP'), ('POP3', 'POP3'), ('FTP', 'FTP'), ('OTHER', 'Other')], max_length=20)),
                ('frecuencia_analisis', models.PositiveSmallIntegerField(default=30, help_text='Días entre análisis automáticos')),
                ('fecha_proxima_revision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='clients.client')),
            ],
            options={
                'db_table': 'certificados',
            },
        ),
        migrations.CreateModel(
            name='VitalityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo/Up'), ('inactivo', 'Inactivo/Down')], max_length=20)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitality_checks', to='certs.certificate')),
            ],
            options={
                'db_table': 'estado_vitalidad',
                'ordering': ['-hora'],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['cliente', 'active'], name='certificado_cliente_e51a83_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['fecha_proxima_revision'], name='certificado_fecha_p_add645_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['protocolo'], name='certificado_protoco_cdd66b_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('ip__isnull', False)), fields=('ip', 'puerto'), name='unique_ip_puerto'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('url__isnull', False)), fields=('url', 'puerto'), name='unique_url_puerto'),
        ),
        migrations.AddIndex(
            model_name='vitalitystatus',
            index=models.Index(fields=['certificado', 'hora'], name='estado_vita_certifi_938510_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalitystatus',
            index=models.Index(fields=['estado'], name='estado_vita_estado_499fde_idx'),
        ),
    ]
