# Generated by Django 5.0.6 on 2025-09-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certificate',
            name='unique_ip_puerto',
        ),
        migrations.RemoveConstraint(
            model_name='certificate',
            name='unique_url_puerto',
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('ip__isnull', False)), fields=('cliente', 'ip', 'puerto'), name='unique_cliente_ip_puerto'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('url__isnull', False)), fields=('cliente', 'url', 'puerto'), name='unique_cliente_url_puerto'),
        ),
    ]
