# Generated by Django 5.0.6 on 2025-09-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0002_remove_certificate_unique_ip_puerto_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certificate',
            name='unique_cliente_ip_puerto',
        ),
        migrations.RemoveConstraint(
            model_name='certificate',
            name='unique_cliente_url_puerto',
        ),
    ]
